export enum ActionType {
	LOADING_USER_ENTITIES = 'LOADING_USER_ENTITIES',
	GET_ALL_USER_ENTITIES = 'GET_ALL_USER_ENTITIES',
	GET_USER_ENTITIES_ERROR = 'GET_USER_ENTITIES_ERROR',
	SELECT_USER_ENTITY = 'SELECT_USER_ENTITY',
}
